### ISSUE TITLE
Inconsistent jetty version because of dependabot updates

### ISSUE THREAD

**Issue by rakeshramakrishnan** [confluentinc/openmessaging-benchmark#12]
Error while starting the distributed mode:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/util/component/Graceful$Shutdown
	at org.eclipse.jetty.server.AbstractConnector.<init>(AbstractConnector.java:156)
	at org.eclipse.jetty.server.AbstractNetworkConnector.<init>(AbstractNetworkConnector.java:44)
	at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:219)
	at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:94)
	at org.eclipse.jetty.server.Server.<init>(Server.java:122)
	at org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider.start(PrometheusMetricsProvider.java:103)
	at io.openmessaging.benchmark.Benchmark.main(Benchmark.java:139)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.component.Graceful$Shutdown
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

This commit seems to break the distributed mode because of jetty version mismatch: https://github.com/confluentinc/openmessaging-benchmark/commit/b163731b56976a66a16e5ec378955f91b81d3a08

What's wrong: the commit has only updated `jetty-server` and not `jetty-util`

Fix: Update `jetty-util` in `benchmark-framework/pom.xml` to the same version as `jetty-server`: `9.4.17.v20190418`

**Comment by aloknnikhil** [comment]
Thanks! Can you submit a PR?

**Comment by rakeshramakrishnan** [comment]
Here's the PR: https://github.com/confluentinc/openmessaging-benchmark/pull/13
