### ISSUE TITLE
bin/benchmark failed with ArrayIndexOutOfBoundsException and NullPointerException

### ISSUE THREAD

**Issue by a484771** [confluentinc/openmessaging-benchmark#20]
I am running a perf test for Apache Kafka and use the following command:

bin/benchmark \
  --drivers driver-kafka/kafka-exactly-once.yaml \
  workloads/simple-workload.yaml

After the command run for about 5 mins, the error message repeatedly as below, but the process is not broken, it keeps running:
09:11:17.616 [kafka-producer-network-thread | producer-1] WARN  i.o.benchmark.worker.LocalWorker - Write error on message
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range. Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1311669 out of bounds for length 1310720
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
	at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkProducer.lambda$sendAsync$0(KafkaBenchmarkProducer.java:49) ~[driver-kafka-0.0.1-SNAPSHOT.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion(KafkaProducer.java:1363) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:228) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.done(ProducerBatch.java:197) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.completeBatch(Sender.java:653) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.completeBatch(Sender.java:634) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.handleProduceResponse(Sender.java:554) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.lambda$sendProduceRequest$0(Sender.java:743) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:566) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:325) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:253) ~[kafka-clients-2.6.0.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

and finally the application break with message:

09:11:40.997 [main] ERROR io.openmessaging.benchmark.Benchmark - Failed to run the workload 'Simple Workload 1 producer on 1 topic' for driver 'driver-kafka/kafka-exactly-once.yaml'
java.lang.NullPointerException: null
	at io.openmessaging.benchmark.Benchmark.lambda$main$0(Benchmark.java:155) ~[classes/:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
	at io.openmessaging.benchmark.Benchmark.lambda$main$1(Benchmark.java:138) ~[classes/:na]
	at java.base/java.util.TreeMap.forEach(TreeMap.java:1002) ~[na:na]
	at io.openmessaging.benchmark.Benchmark.main(Benchmark.java:129) ~[classes/:na]

**Comment by a484771** [comment]
duplicated, remove this issue

**Comment by nicolaferraro** [comment]
> duplicated, remove this issue

What's the original issue of which this is a duplicate @ghost? I'm getting the same error.

**Comment by ricardocajo** [comment]
> > duplicated, remove this issue
> 
> What's the original issue of which this is a duplicate @ghost? I'm getting the same error.

Hey,

Did you end up getting any hint on what might have been the problem?

Thanks!
